version: '3.7'
services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - "./juice-shop-logs:/usr/src/app/logs" # Persistent logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.1
    container_name: filebeat
    volumes:
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "./juice-shop-logs:/usr/src/app/logs" # Read logs from Juice Shop
    depends_on:
      - elasticsearch
    command: ["--strict.perms=false"]
